# Generated by Django 4.2 on 2024-12-04 11:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbmail", "0015_auto_20180926_1206"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="signaldeferreddispatch",
            new_name="dbmail_sign_eta_bd53d1_idx",
            old_fields=("eta", "done"),
        ),
        migrations.AlterField(
            model_name="mailbasetemplate",
            name="message",
            field=ckeditor.fields.RichTextField(
                help_text="Basic template for mail messages. {{content}} tag for msg.",
                verbose_name="Body",
            ),
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="message",
            field=ckeditor.fields.RichTextField(verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="signaldeferreddispatch",
            name="done",
            field=models.BooleanField(null=True),
        ),
    ]
